### ISSUE TITLE
RGB settings not in effect 99% of the time 

### ISSUE THREAD

**Issue by Shaunathanz** [aarron-lee/LegionGoRemapper#21]
I'll preface by saying I've reinstalled this plugin a few times and I'm on the latest Bazzite OS release, latest Legion Go BIOS, and the latest stable Decky, latest controller firmware, and latest stable Steam client. I also am not using the Legion Custom TDP setting, I am using custom fan curve settings. I have ryzenadj installed for TDP control. I have STAPM or "STAMP" enabled.

My controller LEDs are almost always sky blue probably 50% brightness. When I first boot into gaming mode and Decky loads, the RGB settings are applied briefly. Once I start using the controllers however they revert to the sky blue color and stay that way. If I turn the lights off with the plugin, they turn back on in a few seconds to sky blue. When I go to load a game curiously my color settings from the plugin are applied while it processes shaders or whatever, but once the game is officially running it's back to sky blue again.

Anything I can do to help debug or if I'm missing something obvious please let me know.

**Comment by aarron-lee** [comment]
did you disable hhd's LED management? sounds like the plugin is being overwritten by hhd

**Comment by Shaunathanz** [comment]
That was it! Sorry for opening the issue, LegionGoRemapper is amazing so thank you Aaron for making it possible (along with the other contributors)

**Comment by aarron-lee** [comment]
> That was it! Sorry for opening the issue, LegionGoRemapper is amazing so thank you Aarron for making it possible (along with the other contributors)

haha, no worries. I updated the README with some troubleshooting info related to hhd
